### ISSUE TITLE
Error during load server

### ISSUE THREAD

**Issue by ghost** [SupremeMortal/SynapseTransfer#4]
hi i ve got some error during starting server

SynapseTrans-0.0.1-ALPHA.jar' w folderze '/home/mcpe1.0/lob/plugins': while scanning a simple key
 in 'string', line 22, column 3:
      synapse.command.send
      ^
could not find expected ':'
 in 'string', line 23, column 16:
        description: Grants access to send command.
                   ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)                                                                          at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:387)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

00:14:55 [ALERT] while scanning a simple key
 in 'string', line 22, column 3:
      synapse.command.send
      ^
could not find expected ':'
 in 'string', line 23, column 16:
        description: Grants access to send command.
                   ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:137)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:92)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:387)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by SupremeMortal** [comment]
Looks like you edited your yml file incorrectly.
http://yaml-online-parser.appspot.com/
